Feature: Test the equipment section

  As a logged-in fulfilld user
  I want to test the equipment section

  Scenario: The user login into the Fulfilld Web App
    Given I am on the "https://fd.fulfilld.qa/auth/support/login" page
    When I login in fulfilld app
    Then I check the page header is "Today’s Operations Overview"
    
  Scenario: Verify elements visibility for the equipment section
    And I open the settings section
    And I search for "Equipment" section
    Then I check the page header is "Equipment"
    And I check the page sub-header is "View and manage warehouse equipment."
    And I check the data table headers are displayed and are correct for equipment

  Scenario: Verify if user clicks the sidebar logo is routed to the operantions page.
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    When I click the sideBar fulfilld logo
    Then I verify the URL is "https://fd.fulfilld.qa/w/ab8d02d6/operations"

  Scenario: Verify if user clicks the page back button is routed to the settings page.
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    When I click the page info back button
    Then I check the page header is "Settings"

  Scenario: Verify if the user clicks the cancel button the add new equipment modal is closed
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I click the cancel button
    Then I verify the new equipment modal is closed

  Scenario: Verify if the user clicks the close button the new equipment modal is closed
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I click the close button
    Then I verify the new equipment modal is closed

  @skip
  #https://fulfilld.atlassian.net/browse/DEV-2880
  Scenario: Verify the required fields error messages are displayed in the add new equipment modal
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I click the submit button
    Then I check the required error labels are displayed for equipment creation modal

  @skip
  #https://fulfilld.atlassian.net/browse/DEV-2888
  Scenario: Verify the user is able to add a new equipment, and check the data in the equipment's table after creation
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                    | label      | description                                        | status | equipmentType | model | tagId           |
      | automationEquipmentCode | Automation | this is an equipment generated by automation suite | Active | abc           | jkl   | automationId182 |
    And I click the submit button
    And  I filter by "automationEquipmentCode" on equipment term filter
    Then I check the saved equipment info is displayed on the table as follows
      | row | code                    | label      | description                                        | type | model | tagId           | status |
      | 1   | automationEquipmentCode | Automation | this is an equipment generated by automation suite | abc  | jkl   | automationId182 | Active |

  @skip
  #https://fulfilld.atlassian.net/browse/DEV-2888
  Scenario: Verify the user is able to delete an equipment, and confirm it was deleted successfully
    Given I am on the "https://fd.fulfilld.qa/w/ab8d02d6/settings/equipment" page
    Then I check the page header is "Equipment"
    And  I filter by "automationEquipmentCode" on equipment term filter
    Then I check the saved equipment info is displayed on the table as follows
      | row | code                    |
      | 1   | automationEquipmentCode |
    And I click edit equipment button
    And I click the delete button
    And  I filter by "automationEquipmentCode" on equipment term filter
    Then I verify "no results" is displayed on the equipment table