Feature: Test the Equipment section

  As a logged-in fulfilld user
  I want to test the equipment section

  @severity:trivial
  Scenario: The user login into the Fulfilld Web App.
    Given I am on the login page
    When I login in fulfilld app
    Then I check the page header is "Today’s Operations Overview"
    And I remove all test equipments data

  @severity:minor
  Scenario: Verify elements visibility for the equipment section
    Given I open the settings section
    And I search for "Equipment" section
    Then I check the page header is "Equipment"
    And I check the page sub-header is "View and manage warehouse equipment."
    And I check the data table headers are displayed and are correct for equipment

  @severity:minor
  Scenario: Verify that the user is routed to the Operations page when they click the sidebar logo.
    Given I am on the "equipment" page
    Then I check the page header is "Equipment"
    When I click the sideBar fulfilld logo
    Then I verify the URL has "/operations"

  @severity:minor
  Scenario: Verify that the user is routed to the Settings page when they click the back button.
    Given I am on the "equipment" page
    Then I check the page header is "Equipment"
    When I click the page info back button
    Then I check the page header is "Settings"

  @severity:normal
  Scenario: Verify if the user clicks the cancel or close button then the add new equipment modal is closed
    Given I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I click the cancel button
    Then I verify the new equipment modal is closed
    And I click add new equipment button
    And I click the close button
    Then I verify the new equipment modal is closed

  @severity:normal
  Scenario: Verify the required fields error messages are displayed in the add new equipment modal
    Given I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I click the submit button
    Then I check the required error labels are displayed for equipment creation modal

  @severity:critical
  Scenario: Verify the user is able to add a new equipment, and check the data in the equipment's table after creation
    Given I remove all test equipments data
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                    | label                      | description                                        | status | equipmentType | model                | tagId           |
      | automationEquipmentCode | Automation equipment label | This is an equipment generated by automation suite | Active | FL01          | jjkj equipment model | automationId182 |
    And I click the submit button
    Then I check the snackbar message is "Successfully added new equipment: Automation equipment label"
    When I filter by column: "Code" on the equipment section
    And I filter by text "automationEquipmentCode" on the equipment term filter and ensure that a record is displayed
    Then I verify that the previously saved equipment info is displayed on the table as follows
      | row | code                    | label                      | description                                        | type | model                | tagId           | status |
      | 1   | automationEquipmentCode | Automation equipment label | This is an equipment generated by automation suite | FL01 | jjkj equipment model | automationId182 | Active |
    And I remove all test equipments data


  @severity:critical
  Scenario: Verify user can create a new equipment type with mandatory fields only, and validate the data persistence in the equipment types table
    Given I remove all test equipments data
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                    | label                      | status | equipmentType | model                |
      | automationEquipmentCode | Automation equipment label | Active | FL01          | jjkj equipment model |
    And I click the submit button
    Then I check the snackbar message is "Successfully added new equipment: Automation equipment label"
    When I filter by column: "Code" on the equipment section
    And I filter by text "automationEquipmentCode" on the equipment term filter and ensure that a record is displayed
    Then I verify that the previously saved equipment info is displayed on the table as follows
      | row | code                    | label                      | type | model                | status |
      | 1   | automationEquipmentCode | Automation equipment label | FL01 | jjkj equipment model | Active |
    And I remove all test equipments data

  @severity:normal
  Scenario: Verify the persistence of data in the edit form after creation.
    Given I remove all test equipments data
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                    | label                      | description                                        | status | equipmentType | model                | tagId           |
      | automationEquipmentCode | Automation equipment label | This is an equipment generated by automation suite | Active | FL01          | jjkj equipment model | automationId182 |
    And I click the submit button
    When I filter by column: "Code" on the equipment section
    And I filter by text "automationEquipmentCode" on the equipment term filter and ensure that a record is displayed
    And I click the edit button
    Then I verify that the previously saved equipment info is displayed on the edit equipment form
      | code                    | label                      | description                                        | status | equipmentType | model                | tagId           |
      | automationEquipmentCode | Automation equipment label | This is an equipment generated by automation suite | active | FL01          | jjkj equipment model | automationId182 |
    And I remove all test equipments data

  @severity:critical
  Scenario: Verify the user is able to edit an equipment, and check the data in the equipment types's table after updates
    Given I remove all test equipments data
    And I create an equipment thru grahpql endpoint
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    When I filter by column: "Code" on the equipment section
    And I filter by text "AUTOMATION EQUIPMENT FOR EDIT" on the equipment term filter and ensure that a record is displayed
    And I click the edit button
    And I fill in the new equipment info
      | code                           | label                              | description                                         | status   | equipmentType | model                | tagId          |
      | automationEquipmentCodeUpdated | Automation equipment label updated | This is an equipment edited by automation test case | Inactive | MPC02         | ghjf equipment model | automationId41 |
    And I click the submit button
    Then I check the snackbar message is "Successfully updated equipment: Automation equipment label updated"
    When I filter by column: "Code" on the equipment section
    And I filter by text "automationEquipmentCodeUpdated" on the equipment term filter and ensure that a record is displayed
    Then I verify that the previously saved equipment info is displayed on the table as follows
      | row | code                           | label                              | description                                         | type  | model                | tagId          | status   |
      | 1   | automationEquipmentCodeUpdated | Automation equipment label updated | This is an equipment edited by automation test case | MPC02 | ghjf equipment model | automationId41 | Inactive |
    And I remove all test equipment types data

  @severity:critical
  Scenario: Verify the user is able to delete an equipment, and confirm it was deleted successfully
    Given I remove all test equipments data
    And I create an equipment thru grahpql endpoint
    Given I am on the "equipment" page
    Then I check the page header is "Equipment"
    When I filter by column: "Code" on the equipment section
    And I filter by text "AUTOMATION EQUIPMENT FOR EDIT" on the equipment term filter and ensure that a record is displayed
    And I click the edit button
    And I click the delete button
    Then I check the snackbar message is "Successfully deleted equipment: Automation equipment label"
    When I filter by column: "Code" on the equipment section
    And  I filter by text "AUTOMATION EQUIPMENT FOR EDIT" on equipment term filter
    Then I verify "no results" is displayed on the equipment table
    And I remove all test equipments data

  @severity:critical
  Scenario: Verify that the user is not able to duplicate an equipment code during equipment creation.
    Given I remove all test equipments data
    And I create an equipment thru grahpql endpoint
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                          | label                              | status | equipmentType | model                |
      | AUTOMATION EQUIPMENT FOR EDIT | Automation equipment label updated | Active | FL01          | jjkj equipment model |
    And I click the submit button
    Then I check the snackbar error message is "Equipment not unique by code,warehouseId"

  @severity:critical
  Scenario: Verify that the user is not able to duplicate an equipment label during equipment creation.
    Given I remove all test equipments data
    And I create an equipment thru grahpql endpoint
    And I am on the "equipment" page
    Then I check the page header is "Equipment"
    And I click add new equipment button
    And I fill in the new equipment info
      | code                           | label                      | status | equipmentType | model                |
      | automationEquipmentCodeUpdated | Automation equipment label | Active | FL01          | jjkj equipment model |
    And I click the submit button
    Then I check the snackbar error message is "Equipment not unique by label,warehouseId"